name: Backup notion

on:
  push:
  schedule:
    - cron: '5 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Download backup and push to GDrive
      run: python notion
      env:
        NOTION_LOCALE: en
        NOTION_TIMEZONE: 'Europe/London'
        NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
        NOTION_EMAIL: ${{ secrets.NOTION_EMAIL }}
        NOTION_PASSWORD: ${{ secrets.NOTION_PASSWORD }}
        GDRIVE_ROOT_FOLDER_ID: ${{ secrets.GDRIVE_ROOT_FOLDER_ID }}
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
